### ISSUE TITLE
works with 6.4 kernel without any problem

### ISSUE THREAD

**Issue by dga4130-renato** [AndiWeiss/alx-wol#1]
making some changes to the script compiles with 6.4 kernel without any problem. really nice job

just have a look was a 2 minutes job, maybe something better can be done.. thanks really great !!!

uname -a
Linux 6.4.0-060400-generic #202306271339 SMP PREEMPT_DYNAMIC Tue Jun 27 14:26:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

find /lib/modules/$(uname -r) -type f -name '*alx.ko'
/lib/modules/6.4.0-060400-generic/kernel/drivers/net/ethernet/atheros/alx/alx.ko
/lib/modules/6.4.0-060400-generic/updates/dkms/alx.ko

[alx-wol-master.6.4.zip](https://github.com/AndiWeiss/alx-wol/files/11910657/alx-wol-master.6.4.zip)

**Comment by AndiWeiss** [comment]
I'll take a look at that, thank you.
But I need a little bit of time to do so ...

**Comment by AndiWeiss** [comment]
Kernel 6.4 implemented.
I decided to keep the 6.3 patch also for kernel 6.4 - it applies with some lines offset.
Additionally I fixed some installation issues.
