### ISSUE TITLE
ubuntu 24.04 kernel 6.8.7

### ISSUE THREAD

**Issue by dga4130-renato** [AndiWeiss/alx-wol#11]
"alx-wol has been tested on Ubuntu 22.04 and 23.10. With regular kernel updates delieverd by Ubuntu the system works pretty nice."

Upgraded 24.04 worked as a charm !
kernel 6.8.7

**Comment by AndiWeiss** [comment]
Thank you for the hint.
In the case that with a new kernel the patch fails just give me a hint.
I sometimes check the patches but just from time to time, not in a regular time frame.
Adding another patch is not a big deal.
