### ISSUE TITLE
Not working on 6.9.6 Arch kernel

### ISSUE THREAD

**Issue by notherealmarco** [AndiWeiss/alx-wol#14]
```
$ sudo ./install.sh
grep: warning: stray \ before "
grep: warning: stray \ before "
grep: warning: stray \ before "
/etc/initramfs-tools/hooks doesn't exist
continue installation, update of initramfs may fail
Sign command: /usr/lib/modules/6.9.6-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Usage: extract-vmlinux <kernel-image>
extract_kversion_string.sh: /boot/vmlinuz-6.9.6-arch1-1 seems not to be a vmlinuz file
extract_kversion.sh: can't access /var/lib/dkms/alx-wol/2.1/6.9.6-arch1-1/kernel_version_string
gcc_used.sh: can't access /var/lib/dkms/alx-wol/2.1/6.9.6-arch1-1/kernel_version_string
rm: impossibile rimuovere '/var/lib/dkms/alx-wol/2.1/6.9.6-arch1-1/kernel_version_string': File o directory non esistente
Creating symlink /var/lib/dkms/alx-wol/2.1/source -> /usr/src/alx-wol-2.1

Running the pre_build script:
cat: /var/lib/dkms/alx-wol/2.1/build/../6.9.6-arch1-1/kernel_version: File o directory non esistente
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/net/ethernet/atheros/alx?h=v:
2024-07-03 20:07:57 ERRORE 404: Not found.
fetch_kernelparts.sh failed

Building module:
Cleaning build area...(bad exit status: 2)
make -j4 KERNELRELEASE=6.9.6-arch1-1 -C /usr/lib/modules/6.9.6-arch1-1/build M=/var/lib/dkms/alx-wol/2.1/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.9.6-arch1-1 (x86_64)
Consult /var/lib/dkms/alx-wol/2.1/build/make.log for more information.
#### FAILED installation of alx-wol version 2.1 ####
```

Content of `/var/lib/dkms/alx-wol/2.1/build/make.log`:
```
$ cat /var/lib/dkms/alx-wol/2.1/build/make.log
DKMS make.log for alx-wol-2.1 for kernel 6.9.6-arch1-1 (x86_64)
mer 3 lug 2024, 20:08:27, CEST
make: ingresso nella directory «/usr/lib/modules/6.9.6-arch1-1/build»
scripts/Makefile.build:41: /var/lib/dkms/alx-wol/2.1/build/alx/Makefile: File o directory non esistente
make[3]: ***  Nessuna regola per generare l'obiettivo «/var/lib/dkms/alx-wol/2.1/build/alx/Makefile».  Arresto.
make[2]: *** [scripts/Makefile.build:485: /var/lib/dkms/alx-wol/2.1/build/alx] Error 2
make[1]: *** [/usr/lib/modules/6.9.6-arch1-1/build/Makefile:1918: /var/lib/dkms/alx-wol/2.1/build] Error 2
make: *** [Makefile:240: __sub-make] Error 2
make: uscita dalla directory «/usr/lib/modules/6.9.6-arch1-1/build»
```

**Comment by AndiWeiss** [comment]
Hm ... which distro is this?
It doesn't look like Ubuntu, Debian or Proxmox.
Installation fails, so I expect that my alx-wol doesn't know the distri.
Do I get it right: is this Arch linux?

**Comment by AndiWeiss** [comment]
I took a first look in arch Linux, never did that before.
I'll see what I can do, just follow changes in this repo.
May take a while but I'll get it working on arch Linux, too.

**Comment by notherealmarco** [comment]
> is this Arch linux?

that is correct



> May take a while but I'll get it working on arch Linux, too

thanks a lot!

**Comment by AndiWeiss** [comment]
I took a first view, a large part is already working.
But I have a question:
Are you experienced with how Arch Linux handles kernel updates?
I need to know a possibility for doing a kernel update in the way arch linux does it.

**Comment by AndiWeiss** [comment]
new status:
I'm able to install it, but removal doesn't work.
Still several steps to go.

**Comment by AndiWeiss** [comment]
I pushed a new version containing Arch Linux support.
I'm happy to receive comments on it!

**Comment by notherealmarco** [comment]
> I pushed a new version containing Arch Linux support (branch arch_linux). I'm happy to receive comments on it! Please check the news, you have to take care to install some more things before alx-wol installation!

The script works, but it doesn't specifically support my Arch install as I'm using dracut and systemd-boot (most Arch installs uses mkinitpcio and grub), and the script wasn't able to find the kernel file. But I fixed it by specifying it manually in the script. In my case the path was `/efi/<machine-id>/<kernel version>/linux`.

I also had to modify the handleinitrd.sh script as it only supports mkinitcpio and initramfs-tools, so I modified the command with the proper one for my install: `dracut --regenerate-all --force`.

After making these minor changes, it worked perfectly!

**Comment by AndiWeiss** [comment]
Thanks for the hints.
If you can explain what I have to do to configure the Arch in that way I can check for modification.
I just followed the installation explanation.
I expect that it is possible to detect the different mechanisms.

**Comment by notherealmarco** [comment]
> Thanks for the hints. If you can explain what I have to do to configure the Arch in that way I can check for modification. I just followed the installation explanation. I expect that it is possible to detect the different mechanisms.

Sorry, I've only just read your message.
Considering that Arch is a very heterogeneous distro, finding the vmlinuz file might be difficult in some cases, as it strongly depends on how the system has been configured. If your are unable to find it, I would just let the script ask the user for the path.
Anyway, most of the users use mkinitpcio, and in that case your script is already working.

Regarding the `handleinitrd.sh` script, you can just check if the command `mkinitcpio` is available. If not, you execute the dracut's equivalent command, which is: `dracut --regenerate-all --force`.

**Comment by AndiWeiss** [comment]
Hi there,
again thank you for the information.
I'm currently planing to change the mechanisms and when doing so I'll take that into account.
