### ISSUE TITLE
Adding info about proxmox and archlinux branch

### ISSUE THREAD

**Issue by Skav** [AndiWeiss/alx-wol#18]
Hey,

I spend a lot of time today to make this script work on my proxmox machine, and after 30-60 minutes i find out there's separate branch for proxmox and arch - and i only found them, because of some old closed issues on repo - after changing it it just worked without any problem

I think it will be nice for future users to add information about separate branches for proxmox and arch - it shoudn't take much time, but will definitely help people in future

Also - thank you  very much for this script - now i can WoL my Killer E2200 card!

**Comment by AndiWeiss** [comment]
Hi there,
let me say it like this:
I have a plan to bring it all together again.
At the end there will be only one branch again.
But currently I don't have the time to do so ...
The different branches have been created for not disturbing the main branch.
Nice to read that it fits your needs.
