### ISSUE TITLE
Support for kernel 5.15 which is long term in ubuntu 22.04?

### ISSUE THREAD

**Issue by cptX** [AndiWeiss/alx-wol#2]
Would it be possible to provide support for kernel 5.15 which is long term in ubuntu 22.04?

I have Linux Mint 21 (ubuntu 22.04) and the available kernels in the system are the 5.15 family with long term support and the 5.19 with support for short time.

**Comment by AndiWeiss** [comment]
Hi there,
I'll do my very best! :-)
I'm rather sure that  it is possible, I'll add that together with the support for kernel 6.4.

**Comment by AndiWeiss** [comment]
I did a check while implementing kernel 6.4 support.
Kernel 5.15 already works.
