### ISSUE TITLE
6.4.6 kernel fail build

### ISSUE THREAD

**Issue by dga4130-renato** [AndiWeiss/alx-wol#4]
Selezionato il pacchetto linux-headers-6.4.6-060406 non precedentemente selezionato.
(Lettura del database... 260336 file e directory attualmente installati.)
Preparativi per estrarre linux-headers-6.4.6-060406_6.4.6-060406.202307241739_all.deb...
Estrazione di linux-headers-6.4.6-060406 (6.4.6-060406.202307241739)...
Selezionato il pacchetto linux-headers-6.4.6-060406-generic non precedentemente selezionato.
Preparativi per estrarre linux-headers-6.4.6-060406-generic_6.4.6-060406.202307241739_amd64.deb...
Estrazione di linux-headers-6.4.6-060406-generic (6.4.6-060406.202307241739)...
Selezionato il pacchetto linux-image-unsigned-6.4.6-060406-generic non precedentemente selezionato.
Preparativi per estrarre linux-image-unsigned-6.4.6-060406-generic_6.4.6-060406.202307241739_amd64.deb...
Estrazione di linux-image-unsigned-6.4.6-060406-generic (6.4.6-060406.202307241739)...
Selezionato il pacchetto linux-modules-6.4.6-060406-generic non precedentemente selezionato.
Preparativi per estrarre linux-modules-6.4.6-060406-generic_6.4.6-060406.202307241739_amd64.deb...
Estrazione di linux-modules-6.4.6-060406-generic (6.4.6-060406.202307241739)...
Configurazione di linux-headers-6.4.6-060406 (6.4.6-060406.202307241739)...
Configurazione di linux-headers-6.4.6-060406-generic (6.4.6-060406.202307241739)...
/etc/kernel/header_postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.4.6-060406-generic
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Running the pre_build script:

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.4.6-060406-generic -C /lib/modules/6.4.6-060406-generic/build M=/var/lib/dkms/alx-wol/1.4/build...(bad exit status: 2)
ERROR (dkms apport): binary package for alx-wol: 1.4 not found
Error! Bad return status for module build on kernel: 6.4.6-060406-generic (x86_64)
Consult /var/lib/dkms/alx-wol/1.4/build/make.log for more information.
dkms autoinstall on 6.4.6-060406-generic/x86_64 failed for alx-wol(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
   ...fail!
run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
dpkg: errore nell'elaborare il pacchetto linux-headers-6.4.6-060406-generic (--install):
 il sottoprocesso installato pacchetto linux-headers-6.4.6-060406-generic script post-installation ha restituito lo stato di errore 1
Configurazione di linux-modules-6.4.6-060406-generic (6.4.6-060406.202307241739)...
Configurazione di linux-image-unsigned-6.4.6-060406-generic (6.4.6-060406.202307241739)...
I: /boot/vmlinuz.old is now a symlink to vmlinuz-6.2.0-26-generic
I: /boot/initrd.img.old is now a symlink to initrd.img-6.2.0-26-generic
I: /boot/vmlinuz is now a symlink to vmlinuz-6.4.6-060406-generic
I: /boot/initrd.img is now a symlink to initrd.img-6.4.6-060406-generic
Elaborazione dei trigger per linux-image-unsigned-6.4.6-060406-generic (6.4.6-060406.202307241739)...
/etc/kernel/postinst.d/dkms:
 * dkms: running auto installation service for kernel 6.4.6-060406-generic
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der

Running the pre_build script:

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.4.6-060406-generic -C /lib/modules/6.4.6-060406-generic/build M=/var/lib/dkms/alx-wol/1.4/build...(bad exit status: 2)
ERROR (dkms apport): binary package for alx-wol: 1.4 not found
Error! Bad return status for module build on kernel: 6.4.6-060406-generic (x86_64)
Consult /var/lib/dkms/alx-wol/1.4/build/make.log for more information.
dkms autoinstall on 6.4.6-060406-generic/x86_64 failed for alx-wol(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
   ...fail!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: errore nell'elaborare il pacchetto linux-image-unsigned-6.4.6-060406-generic (--install):
 il sottoprocesso installato pacchetto linux-image-unsigned-6.4.6-060406-generic script post-installation ha restituito lo stato di errore 1
Si sono verificati degli errori nell'elaborazione:
 linux-headers-6.4.6-060406-generic
 linux-image-unsigned-6.4.6-060406-generic

**Comment by dga4130-renato** [comment]
cat /var/lib/dkms/alx-wol/1.4/build/make.log
DKMS make.log for alx-wol-1.4 for kernel 6.4.6-060406-generic (x86_64)
lun 24 lug 2023, 22:23:00, CEST
make: ingresso nella directory «/usr/src/linux-headers-6.4.6-060406-generic»
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.1.0-8ubuntu1) 13.1.0
  You are using:           
  CC [M]  /var/lib/dkms/alx-wol/1.4/build/alx_6.4/main.o
/bin/sh: 1: gcc-13: not found
make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/alx-wol/1.4/build/alx_6.4/main.o] Errore 127
make[1]: *** [scripts/Makefile.build:494: /var/lib/dkms/alx-wol/1.4/build/alx_6.4] Errore 2
make: *** [Makefile:2038: /var/lib/dkms/alx-wol/1.4/build] Errore 2
make: uscita dalla directory «/usr/src/linux-headers-6.4.6-060406-generic»

**Comment by dga4130-renato** [comment]
gcc-13 missing. installed was ok, maybe a warn about not building without that version of gcc would be better for many people that doesnt know how to read logs

**Comment by AndiWeiss** [comment]
That's interesting.
I tried with my clean 22.04.2 and didn't face that issue. Builds like a charm with gcc-12.
Which system did you use?
Nevertheless I'll take a look if I can check the compiler dependencies and see if I can add that.
But - sorry, will take a while ...

**Comment by dga4130-renato** [comment]
Log says fail because no GCC 1.3 .. Ubuntu 23

Il lun 24 lug 2023, 23:12 AndiWeiss ***@***.***> ha scritto:

**Comment by AndiWeiss** [comment]
From my point of view this issue is a missing dependency in the kernel package from Ubuntu.
I created a workaround:
In the case that 6.4.x shall be build and gcc-13 isn't found I use gcc-12 instead.
I tested that and it works fine.
