### ISSUE TITLE
kernel 6.5 >

### ISSUE THREAD

**Issue by dga4130-renato** [AndiWeiss/alx-wol#6]
Hi,
installed today ubuntu 23.10 and tried to run the script, but no success... still mismatch version of gcc13.
neither kernel 6.6.x can be compiled due to this mismatch.
it's looking for gcc 13.2.0-4ubuntu2 and the release installed  is 13.2.0-4ubuntu3
maybe is there an option to pass when compiling to no check the compiler and go ahead ?

**Comment by AndiWeiss** [comment]
This has nothing to do with the compiler.
As you can read in the readme the current version supports kernel version up to 6.4.
the current version simply doesn't support kernel 6.5.
I'll add it soon.
